version: '3.5'
services:
  loterioma_jenkins:
    build: .docker/jenkins
    container_name: loterioma_jenkins
    stdin_open: true
    tty: true
    env_file:
      - variables.env
    ports:
      - 5549:8080
      - 50000:50000
    environment:
      - JENKINS_USER=JENKINS_USER
    volumes:
      - /var/www/html/respberryvision:/var/jenkins_home/workspace
      - /var/applications/loterioma/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock